version: '3'

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh pnpm start:dev
    volumes:
    - .:/home/node/app
    tty: true
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
  
  redis:
    container_name: redis
    image: redis:6
    restart: always
    ports:
      - '14930:14930'